### ISSUE TITLE
[Mgmt] Transfer the repo to a redhat github managed org

### ISSUE THREAD

**Issue by josecastillolema** [mukrishn/sriov-prep#5]
IMO this repo should be transfered to a redhat github managed organization, i.e.: [redhat-performance](https://github.com/redhat-performance)

**Comment by mukrishn** [comment]
True, if it has been used frequently we can move this under webfuse perhaps, it is a simple playbook so better not to be on its own repository :thinking:
or if it is shared across team then it can be on its own.
